version: "3" # composeファイルのバージョン
services:
  app: # サービス名
    build: ./backend/ # ①ビルドに使うDockerfileの場所
    tty: true # ②コンテナの永続化
    ports: # ホストOSのポートとコンテナのポートをつなげる
        - "9990"
    volumes:
        - ./backend:/go/src/Spotify_new_releases # ③マウントディレクトリ
    environment:
      TZ: Asia/Tokyo
    env_file:
        - backend_app.env
    depends_on:
        - mysql
    networks:
      - app1
    restart: always
    command: "go run ./app/cmd/main.go"
    container_name: "backend-container"

  mysql:
    build: ./mysql/
    volumes:
        # 初期データを投入するSQLが格納されているdir
        - ./mysql/init:/docker-entrypoint-initdb.d
        # 永続化するときにマウントするdir
        - db-store:/var/lib/mysql
    #environment:
        #- MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    env_file:
        - mysql.env
    ports:
        - "3306:3306"
    networks:
        - app1
    container_name: "mysql-container"

volumes:
  db-store:
  letsencrypt:

networks:
  app1:
    external: true